# Stage 1: Build the app
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install 

# Copy the rest of the app
COPY . .

# Expose the port your app runs on
EXPOSE 5555

# Start the app
CMD ["node", "index.js"]
