name: Docker CI/CD

on:
  push:
    branches:
      - main  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t chinuboss/bookstore-backend:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push chinuboss/bookstore-backend:latest

      # SSH to your server and deploy
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull chinuboss/bookstore-backend:latest
            docker stop bookstore-backend || true
            docker rm bookstore-backend || true
            docker run -d -p 5555:5555 --name bookstore-backend \
              -e MONGODB_URI=${{ secrets.SERVER_MONGODB_URI }} \
              chinuboss/bookstore-backend:latest
